Name: MyApp
Version: 0.1.0
Link: https://github.com/Webiny/Webiny
Description: Example app to show the basic structure of frontend and backend apps.
Author:
    Name: Webiny LTD
    Email: info@webiny.com
    Link: https://www.webiny.com